# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

scale_factor = 1.3
theme = "catppuccin-mocha"

[font]
family = "Maple Mono NF CN"

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"
local = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

[buffer.date_separators]
format = "%A, %-d %B %Y"

[buffer.server_messages.condense]
messages = ["change-nick", "join", "part", "quit"]
dimmed = 0.7

[buffer.server_messages.topic]
enabled = false

[servers.omglol]
server = "irc.social.lol"
nickname = "helenchong"
realname = "Helen Chong (they/she)"

[servers.omglol.sasl.plain]
username = "helenchong"
password_file = "~/.config/halloy/passwords/omglol"
